import { DiseaseProgram, Gene, MetabolicPathwayLayer, MetabolicRoute, Pathway, Tissue } from './types';

// ============================================================
// TISSUES — anchors on the body model. ids match SVG region ids.
// ============================================================
export const TISSUES: Tissue[] = [
  { id: 'brain',     name: 'Brain',     system: 'Nervous',    description: 'CNS — cortex, microglia, BBB interface.' },
  { id: 'thyroid',   name: 'Thyroid',   system: 'Endocrine',  description: 'T3/T4 hormone synthesis, metabolic set-point.' },
  { id: 'lungs',     name: 'Lungs',     system: 'Respiratory',description: 'Alveolar epithelium, resident immune cells.' },
  { id: 'heart',     name: 'Heart',     system: 'Cardiovascular', description: 'Cardiomyocytes, vascular endothelium.' },
  { id: 'liver',     name: 'Liver',     system: 'Hepatic',    description: 'Hepatocytes, glucose & lipid metabolism, acute phase.' },
  { id: 'pancreas',  name: 'Pancreas',  system: 'Endocrine',  description: 'β-cell insulin secretion, exocrine enzymes.' },
  { id: 'stomach',   name: 'Stomach',   system: 'Digestive',  description: 'Gastric mucosa, secretory epithelium.' },
  { id: 'intestine', name: 'Intestine', system: 'Digestive',  description: 'Gut epithelium, microbiota interface, GLP-1.' },
  { id: 'kidney',    name: 'Kidneys',   system: 'Renal',      description: 'Nephron filtration, RAAS signaling.' },
  { id: 'spleen',    name: 'Spleen',    system: 'Immune',     description: 'Lymphocyte reservoir, antigen filtration.' },
  { id: 'adipose',   name: 'Adipose',   system: 'Metabolic',  description: 'Adipocytes, adipokine secretion (leptin, adiponectin).' },
  { id: 'muscle',    name: 'Skeletal Muscle', system: 'Musculoskeletal', description: 'Insulin-stimulated glucose uptake, GLUT4.' },
  { id: 'breast',    name: 'Breast',    system: 'Glandular',  description: 'Mammary epithelium, ductal & lobular tissue.' },
  { id: 'bone_marrow', name: 'Bone Marrow', system: 'Immune', description: 'Hematopoiesis, myeloid & lymphoid lineages.' },
  { id: 'skin',      name: 'Skin',      system: 'Integumentary', description: 'Keratinocytes, Langerhans cells, barrier immunity.' },
];

// ============================================================
// PATHWAYS
// ============================================================
export const PATHWAYS: Pathway[] = [
  { id: 'nfkb',          name: 'NF-κB Signaling',           category: 'Immune signaling',    description: 'Master inflammatory transcription program.' },
  { id: 'jak_stat',      name: 'JAK-STAT',                  category: 'Cytokine signaling',  description: 'Type I/II cytokine receptor → STAT transcription.' },
  { id: 'ifn_response',  name: 'Interferon Response',       category: 'Antiviral immunity',  description: 'ISG-driven antiviral and antiproliferative state.' },
  { id: 'insulin',       name: 'Insulin / PI3K-AKT',        category: 'Metabolic signaling', description: 'Glucose uptake, glycogenesis, anabolic growth.' },
  { id: 'mtor',          name: 'mTOR',                      category: 'Growth & metabolism', description: 'Nutrient sensing, protein synthesis, autophagy gate.' },
  { id: 'ampk',          name: 'AMPK Energy Sensing',       category: 'Metabolic signaling', description: 'Low energy → catabolism, fatty acid oxidation.' },
  { id: 'glycolysis',    name: 'Glycolysis',                category: 'Core metabolism',     description: 'Glucose → pyruvate, ATP and biosynthetic precursors.' },
  { id: 'tca_cycle',     name: 'TCA Cycle',                  category: 'Core metabolism',     description: 'Acetyl-CoA oxidation through citrate, succinate and malate.' },
  { id: 'oxphos',        name: 'Oxidative Phosphorylation', category: 'Core metabolism',     description: 'ETC-driven ATP production at the mitochondria.' },
  { id: 'pyruvate_metabolism', name: 'Pyruvate Metabolism', category: 'Core metabolism', description: 'Pyruvate routing into lactate, alanine, oxaloacetate or acetyl-CoA.' },
  { id: 'glycogen_metabolism', name: 'Glycogen Metabolism', category: 'Glucose storage', description: 'Glucose storage and mobilization through glycogenesis and glycogenolysis.' },
  { id: 'pentose_phosphate', name: 'Pentose Phosphate Pathway', category: 'Redox and ribose', description: 'G6P diversion into NADPH, ribose-5-phosphate and nucleotide precursors.' },
  { id: 'fatty_acid_oxidation', name: 'Fatty Acid β-Oxidation', category: 'Lipid metabolism', description: 'Mitochondrial import and stepwise acetyl-CoA generation from fatty acids.' },
  { id: 'lipogenesis',   name: 'De Novo Lipogenesis',        category: 'Lipid metabolism',    description: 'Citrate export → acetyl-CoA → malonyl-CoA → palmitate synthesis.' },
  { id: 'ketone_bodies', name: 'Ketone Body Metabolism', category: 'Lipid metabolism', description: 'Hepatic ketogenesis and peripheral ketone utilization under fasting or stress.' },
  { id: 'triglyceride_metabolism', name: 'Triacylglycerol Metabolism', category: 'Lipid metabolism', description: 'Glycerolipid synthesis, storage, lipolysis and fatty-acid release.' },
  { id: 'phospholipid_metabolism', name: 'Phospholipid / Sphingolipid Metabolism', category: 'Membrane lipids', description: 'Membrane phospholipid, ceramide and sphingolipid remodeling.' },
  { id: 'gluconeogenesis', name: 'Gluconeogenesis',          category: 'Glucose metabolism',  description: 'Hepatic glucose production from lactate, glycerol and amino acids.' },
  { id: 'lactate_shuttle', name: 'Lactate Shuttle',          category: 'Carbon flux',         description: 'LDH-driven pyruvate/lactate exchange across tissues and immune states.' },
  { id: 'cholesterol',   name: 'Cholesterol / Mevalonate',   category: 'Lipid metabolism',    description: 'Acetyl-CoA to sterols, prenylation substrates and membrane programs.' },
  { id: 'steroid_hormone', name: 'Steroid Hormone Biosynthesis', category: 'Hormone metabolism', description: 'Cholesterol conversion to adrenal, gonadal and local steroid hormones.' },
  { id: 'bile_acid', name: 'Bile Acid Synthesis', category: 'Liver lipid handling', description: 'Cholesterol-derived bile acid production, conjugation and enterohepatic cycling.' },
  { id: 'one_carbon',    name: 'One-Carbon / Folate Cycle',  category: 'Nucleotide metabolism', description: 'Methyl donors for nucleotide synthesis, redox balance and epigenetic state.' },
  { id: 'purine',        name: 'Purine Metabolism',          category: 'Nucleotide metabolism', description: 'ATP/GTP turnover, salvage and inflammatory purinergic signaling.' },
  { id: 'pyrimidine', name: 'Pyrimidine Metabolism', category: 'Nucleotide metabolism', description: 'UMP/CTP/dTMP synthesis, salvage and catabolism for proliferating tissues.' },
  { id: 'amino_acid_metabolism', name: 'Amino Acid Metabolism', category: 'Nitrogen metabolism', description: 'Transamination, carbon skeleton routing and amino-acid biosynthesis/degradation.' },
  { id: 'urea_cycle', name: 'Urea Cycle', category: 'Nitrogen disposal', description: 'Ammonia detoxification through ornithine, citrulline, argininosuccinate and urea.' },
  { id: 'heme_porphyrin', name: 'Heme / Porphyrin Metabolism', category: 'Cofactor metabolism', description: 'Porphyrin biosynthesis and heme turnover for erythroid and hepatic function.' },
  { id: 'vitamin_coenzyme', name: 'Vitamins / Coenzymes', category: 'Cofactor metabolism', description: 'B-vitamin and coenzyme-linked metabolic support for redox and carbon transfer.' },
  { id: 'catecholamine', name: 'Catecholamine Biosynthesis', category: 'Neurotransmitter metabolism', description: 'Tyrosine conversion to dopamine, norepinephrine and epinephrine.' },
  { id: 'glutathione_redox', name: 'Glutathione / Redox Buffering', category: 'Redox metabolism', description: 'NADPH-supported glutathione cycling and oxidative stress defense.' },
  { id: 'xenobiotic_detox', name: 'Xenobiotic / Drug Metabolism', category: 'Detoxification', description: 'Cytochrome P450, conjugation and transporter-linked clearance programs.' },
  { id: 'apoptosis',     name: 'Intrinsic Apoptosis',       category: 'Cell fate',           description: 'BAX/BAK pore → cytochrome c → caspase cascade.' },
  { id: 'er_stress',     name: 'ER Stress / UPR',           category: 'Proteostasis',        description: 'Unfolded protein response, IRE1/PERK/ATF6 arms.' },
  { id: 'estrogen',      name: 'Estrogen Receptor',         category: 'Nuclear receptor',    description: 'ERα-driven proliferation in hormone-sensitive tissues.' },
  { id: 'pi3k_her2',     name: 'HER2 / PI3K-AKT-MTOR',      category: 'Oncogenic signaling', description: 'ERBB2 amplification → AKT/mTOR proliferation drive.' },
  { id: 'complement',    name: 'Complement Cascade',        category: 'Innate immunity',     description: 'C3/C5 opsonization and MAC formation.' },
  { id: 'tnf',           name: 'TNF Signaling',             category: 'Cytokine signaling',  description: 'TNFR → NF-κB / apoptosis bifurcation.' },
  { id: 'microglia',     name: 'Microglial Activation',     category: 'Neuro-immune',        description: 'CNS-resident macrophage priming and cytokine release.' },
];

// ============================================================
// GENES / PROTEINS
// ============================================================
export const GENES: Gene[] = [
  { id: 'IL6',     name: 'Interleukin 6',                   proteinClass: 'Cytokine', description: 'Pro-inflammatory cytokine, acute phase driver.' },
  { id: 'TNF',     name: 'Tumor Necrosis Factor',           proteinClass: 'Cytokine', description: 'Master inflammatory cytokine.' },
  { id: 'IL1B',    name: 'Interleukin 1 Beta',              proteinClass: 'Cytokine', description: 'Inflammasome output, fever and recruitment.' },
  { id: 'NFKB1',   name: 'NF-κB p50 subunit',               proteinClass: 'Transcription factor', description: 'Inflammatory transcription program.' },
  { id: 'STAT1',   name: 'STAT1',                           proteinClass: 'Transcription factor', description: 'IFN-γ / antiviral transcription.' },
  { id: 'STAT3',   name: 'STAT3',                           proteinClass: 'Transcription factor', description: 'IL-6 family signaling output.' },
  { id: 'IFNG',    name: 'Interferon Gamma',                proteinClass: 'Cytokine', description: 'Type II IFN, macrophage activation.' },
  { id: 'INSR',    name: 'Insulin Receptor',                proteinClass: 'Receptor tyrosine kinase', description: 'Insulin binding → IRS/PI3K cascade.' },
  { id: 'IRS1',    name: 'Insulin Receptor Substrate 1',    proteinClass: 'Adapter', description: 'Key insulin signaling node, Ser-phosphorylated under IR.' },
  { id: 'AKT1',    name: 'AKT1 / PKB',                      proteinClass: 'Kinase', description: 'Anabolic, pro-survival kinase node.' },
  { id: 'GLUT4',   name: 'SLC2A4 / GLUT4',                  proteinClass: 'Transporter', description: 'Insulin-responsive glucose transporter.' },
  { id: 'PPARG',   name: 'PPARγ',                           proteinClass: 'Nuclear receptor', description: 'Adipocyte differentiation, insulin sensitization.' },
  { id: 'LEP',     name: 'Leptin',                          proteinClass: 'Hormone', description: 'Adipose-derived satiety signal.' },
  { id: 'TP53',    name: 'TP53',                            proteinClass: 'Tumor suppressor', description: 'Genome guardian, apoptosis under stress.' },
  { id: 'ERBB2',   name: 'HER2 / ERBB2',                    proteinClass: 'Receptor tyrosine kinase', description: 'Amplified in ~20% of breast cancers.' },
  { id: 'ESR1',    name: 'Estrogen Receptor α',             proteinClass: 'Nuclear receptor', description: 'Drives proliferation in ER+ breast cancer.' },
  { id: 'BRCA1',   name: 'BRCA1',                           proteinClass: 'DNA repair', description: 'Homologous recombination, hereditary breast cancer.' },
  { id: 'MKI67',   name: 'Ki-67',                           proteinClass: 'Proliferation marker', description: 'Cell cycle activity readout.' },
  { id: 'APOE',    name: 'Apolipoprotein E',                proteinClass: 'Lipid transport', description: 'CNS lipid handling, AD risk allele ε4.' },
  { id: 'TREM2',   name: 'TREM2',                           proteinClass: 'Receptor', description: 'Microglial sensor for damage signals.' },
  { id: 'GFAP',    name: 'GFAP',                            proteinClass: 'Cytoskeletal', description: 'Astrocyte reactivity marker.' },
  { id: 'ACE2',    name: 'ACE2',                            proteinClass: 'Receptor / peptidase', description: 'SARS-CoV-2 entry receptor; RAAS regulation.' },
  { id: 'ISG15',   name: 'ISG15',                           proteinClass: 'Ubiquitin-like', description: 'Canonical interferon-stimulated gene.' },
  { id: 'MX1',     name: 'MX1',                             proteinClass: 'GTPase', description: 'Antiviral interferon-stimulated gene.' },
  { id: 'OAS1',    name: 'OAS1',                            proteinClass: 'Synthetase', description: 'dsRNA sensor, RNase L pathway.' },
  { id: 'CRP',     name: 'C-Reactive Protein',              proteinClass: 'Acute phase', description: 'Hepatic acute phase reactant, IL-6 driven.' },
  { id: 'HK2',     name: 'Hexokinase 2',                    proteinClass: 'Enzyme', description: 'First committed glycolytic phosphorylation step.' },
  { id: 'LDHA',    name: 'Lactate Dehydrogenase A',         proteinClass: 'Enzyme', description: 'Pyruvate to lactate conversion in high glycolytic flux.' },
  { id: 'PDHA1',   name: 'Pyruvate Dehydrogenase E1α',      proteinClass: 'Enzyme', description: 'Links glycolysis to mitochondrial acetyl-CoA.' },
  { id: 'CPT1A',   name: 'Carnitine Palmitoyltransferase 1A', proteinClass: 'Enzyme', description: 'Controls mitochondrial long-chain fatty acid entry.' },
  { id: 'ACACA',   name: 'Acetyl-CoA Carboxylase Alpha',    proteinClass: 'Enzyme', description: 'Generates malonyl-CoA for lipogenesis and FAO inhibition.' },
  { id: 'FASN',    name: 'Fatty Acid Synthase',             proteinClass: 'Enzyme', description: 'Builds palmitate during anabolic lipid synthesis.' },
  { id: 'HMGCR',   name: 'HMG-CoA Reductase',               proteinClass: 'Enzyme', description: 'Rate-limiting mevalonate/cholesterol synthesis enzyme.' },
  { id: 'SHMT2',   name: 'Serine Hydroxymethyltransferase 2', proteinClass: 'Enzyme', description: 'Mitochondrial one-carbon flux for nucleotide synthesis.' },
  { id: 'XDH',     name: 'Xanthine Dehydrogenase',          proteinClass: 'Enzyme', description: 'Purine catabolism and oxidative inflammatory tone.' },
  { id: 'G6PD',    name: 'Glucose-6-Phosphate Dehydrogenase', proteinClass: 'Enzyme', description: 'Rate-limiting oxidative pentose phosphate enzyme for NADPH generation.' },
  { id: 'PKM',     name: 'Pyruvate Kinase M',               proteinClass: 'Enzyme', description: 'Terminal glycolytic kinase controlling pyruvate and ATP formation.' },
  { id: 'PDK4',    name: 'Pyruvate Dehydrogenase Kinase 4', proteinClass: 'Kinase', description: 'Inhibits PDH and diverts pyruvate away from mitochondrial oxidation.' },
  { id: 'GYS1',    name: 'Glycogen Synthase 1',             proteinClass: 'Enzyme', description: 'Muscle glycogen synthesis under insulin and energy signals.' },
  { id: 'PYGL',    name: 'Glycogen Phosphorylase L',        proteinClass: 'Enzyme', description: 'Hepatic glycogenolysis and glucose mobilization.' },
  { id: 'G6PC',    name: 'Glucose-6-Phosphatase Catalytic Subunit', proteinClass: 'Enzyme', description: 'Final hepatic and renal gluconeogenic glucose release step.' },
  { id: 'PCK1',    name: 'Phosphoenolpyruvate Carboxykinase 1', proteinClass: 'Enzyme', description: 'Cytosolic PEPCK, a control point for gluconeogenesis.' },
  { id: 'HADHA',   name: 'Hydroxyacyl-CoA Dehydrogenase Trifunctional Multienzyme Complex Alpha', proteinClass: 'Enzyme', description: 'Mitochondrial long-chain fatty acid beta-oxidation enzyme.' },
  { id: 'BDH1',    name: '3-Hydroxybutyrate Dehydrogenase 1', proteinClass: 'Enzyme', description: 'Ketone body interconversion and peripheral ketone utilization.' },
  { id: 'DGAT2',   name: 'Diacylglycerol O-Acyltransferase 2', proteinClass: 'Enzyme', description: 'Triacylglycerol synthesis in liver and adipose tissue.' },
  { id: 'LIPE',    name: 'Hormone-Sensitive Lipase',        proteinClass: 'Enzyme', description: 'Lipolysis enzyme mobilizing stored triacylglycerol.' },
  { id: 'SCD',     name: 'Stearoyl-CoA Desaturase',         proteinClass: 'Enzyme', description: 'Monounsaturated fatty acid synthesis and lipogenic remodeling.' },
  { id: 'CYP7A1',  name: 'Cholesterol 7 Alpha-Hydroxylase', proteinClass: 'Cytochrome P450', description: 'Rate-limiting bile acid synthesis enzyme in liver.' },
  { id: 'CYP11A1', name: 'Cholesterol Side-Chain Cleavage Enzyme', proteinClass: 'Cytochrome P450', description: 'Initiates steroid hormone biosynthesis from cholesterol.' },
  { id: 'CPS1',    name: 'Carbamoyl-Phosphate Synthase 1',  proteinClass: 'Enzyme', description: 'Mitochondrial entry enzyme for the urea cycle.' },
  { id: 'ASS1',    name: 'Argininosuccinate Synthase 1',    proteinClass: 'Enzyme', description: 'Urea cycle citrulline-to-argininosuccinate step.' },
  { id: 'ALAS2',   name: '5-Aminolevulinate Synthase 2',    proteinClass: 'Enzyme', description: 'Erythroid heme biosynthesis initiation enzyme.' },
  { id: 'DHODH',   name: 'Dihydroorotate Dehydrogenase',    proteinClass: 'Enzyme', description: 'Mitochondrial pyrimidine synthesis enzyme linked to respiration.' },
  { id: 'TYMS',    name: 'Thymidylate Synthase',            proteinClass: 'Enzyme', description: 'dTMP synthesis for DNA replication and repair.' },
  { id: 'COMT',    name: 'Catechol-O-Methyltransferase',    proteinClass: 'Enzyme', description: 'Catecholamine methylation and clearance.' },
  { id: 'TH',      name: 'Tyrosine Hydroxylase',            proteinClass: 'Enzyme', description: 'Rate-limiting catecholamine biosynthesis enzyme.' },
  { id: 'GCLC',    name: 'Glutamate-Cysteine Ligase Catalytic Subunit', proteinClass: 'Enzyme', description: 'Rate-limiting glutathione synthesis enzyme.' },
  { id: 'CYP3A4',  name: 'Cytochrome P450 3A4',             proteinClass: 'Cytochrome P450', description: 'Major hepatic and intestinal xenobiotic metabolism enzyme.' },
  { id: 'UGT1A1',  name: 'UDP Glucuronosyltransferase 1A1', proteinClass: 'Transferase', description: 'Glucuronidation of bilirubin, hormones and xenobiotics.' },
];

export const METABOLIC_PATHWAY_LAYERS: MetabolicPathwayLayer[] = [
  {
    id: 'glycolysis',
    name: 'Glycolysis',
    category: 'Core carbon',
    compartment: 'Cytoplasm',
    summary: 'Glucose is converted through G6P, triose phosphates and pyruvate to generate ATP and biosynthetic branch points.',
    metabolites: ['Glucose', 'G6P', 'F1,6BP', 'G3P', 'Pyruvate', 'ATP'],
    enzymes: ['HK2', 'PKM', 'LDHA'],
    tissueFlux: [
      { ref: 'muscle', state: 'up', weight: 0.9, synthesisRate: 0.92, role: 'High contraction-linked ATP demand' },
      { ref: 'brain', state: 'up', weight: 0.82, synthesisRate: 0.82, role: 'Glucose-biased neural energy' },
      { ref: 'heart', state: 'up', weight: 0.66, synthesisRate: 0.68, role: 'Rapid ATP buffering under stress' },
      { ref: 'liver', state: 'dysregulated', weight: 0.62, synthesisRate: 0.58, role: 'Glucose handling and carbon redistribution' },
      { ref: 'breast', state: 'up', weight: 0.6, synthesisRate: 0.72, role: 'Tumor-like Warburg flux in the cancer story' },
    ],
  },
  {
    id: 'pyruvate_metabolism',
    name: 'Pyruvate Metabolism',
    category: 'Core carbon',
    compartment: 'Cytoplasm · mitochondria',
    summary: 'Pyruvate is routed to lactate, alanine, oxaloacetate or acetyl-CoA depending on oxygen, PDH control and tissue state.',
    metabolites: ['Pyruvate', 'Lactate', 'Alanine', 'Oxaloacetate', 'Acetyl-CoA'],
    enzymes: ['PDHA1', 'PDK4', 'LDHA'],
    tissueFlux: [
      { ref: 'liver', state: 'dysregulated', weight: 0.84, synthesisRate: 0.78, role: 'Controls lactate/alanine recycling and glucose output' },
      { ref: 'muscle', state: 'dysregulated', weight: 0.72, synthesisRate: 0.74, role: 'Exercise and insulin-resistance lactate exchange' },
      { ref: 'heart', state: 'up', weight: 0.7, synthesisRate: 0.72, role: 'PDH-dependent acetyl-CoA supply' },
      { ref: 'brain', state: 'up', weight: 0.56, synthesisRate: 0.58, role: 'Lactate shuttle and neuronal mitochondrial input' },
    ],
  },
  {
    id: 'tca_cycle',
    name: 'TCA Cycle',
    category: 'Mitochondrial carbon',
    compartment: 'Mitochondrial matrix',
    summary: 'Acetyl-CoA enters citrate, alpha-ketoglutarate, succinyl-CoA, fumarate, malate and oxaloacetate to feed NADH/FADH2.',
    metabolites: ['Acetyl-CoA', 'Citrate', 'alpha-KG', 'Succinyl-CoA', 'Fumarate', 'Malate', 'Oxaloacetate'],
    enzymes: ['PDHA1', 'HADHA', 'BDH1'],
    tissueFlux: [
      { ref: 'heart', state: 'up', weight: 0.96, synthesisRate: 0.96, role: 'Continuous mitochondrial ATP production' },
      { ref: 'muscle', state: 'up', weight: 0.82, synthesisRate: 0.84, role: 'Oxidative fibers and exercise demand' },
      { ref: 'liver', state: 'up', weight: 0.78, synthesisRate: 0.76, role: 'Anaplerosis and acetyl-CoA routing' },
      { ref: 'brain', state: 'up', weight: 0.74, synthesisRate: 0.72, role: 'Neuronal oxidative metabolism' },
      { ref: 'kidney', state: 'up', weight: 0.68, synthesisRate: 0.66, role: 'High mitochondrial solute transport burden' },
    ],
  },
  {
    id: 'oxphos',
    name: 'Oxidative Phosphorylation',
    category: 'ATP formation',
    compartment: 'Mitochondrial inner membrane',
    summary: 'NADH and ubiquinol electron flow drives proton translocation and ATP synthase-dependent ATP formation.',
    metabolites: ['NADH', 'UQH2', 'H+', 'O2', 'ADP', 'ATP'],
    enzymes: ['PDHA1', 'DHODH', 'BDH1'],
    tissueFlux: [
      { ref: 'heart', state: 'up', weight: 1, synthesisRate: 1, role: 'Highest continuous ATP turnover' },
      { ref: 'brain', state: 'up', weight: 0.9, synthesisRate: 0.9, role: 'Synaptic energy and ion gradients' },
      { ref: 'kidney', state: 'up', weight: 0.82, synthesisRate: 0.82, role: 'Tubular transport ATP load' },
      { ref: 'muscle', state: 'up', weight: 0.78, synthesisRate: 0.8, role: 'Oxidative phosphorylation during sustained work' },
    ],
  },
  {
    id: 'glycogen_metabolism',
    name: 'Glycogen Metabolism',
    category: 'Glucose storage',
    compartment: 'Cytoplasm',
    summary: 'Glycogen buffers blood and contractile glucose demand through synthesis and phosphorylase-mediated mobilization.',
    metabolites: ['G6P', 'G1P', 'UDP-glucose', 'Glycogen', 'Glucose'],
    enzymes: ['GYS1', 'PYGL', 'G6PC'],
    tissueFlux: [
      { ref: 'liver', state: 'dysregulated', weight: 0.88, synthesisRate: 0.82, role: 'Blood glucose buffer and fasting output' },
      { ref: 'muscle', state: 'down', weight: 0.78, synthesisRate: 0.72, role: 'Insulin-sensitive glycogen storage' },
      { ref: 'brain', state: 'neutral', weight: 0.3, synthesisRate: 0.28, role: 'Astrocyte glycogen reserve' },
    ],
  },
  {
    id: 'gluconeogenesis',
    name: 'Gluconeogenesis',
    category: 'Glucose production',
    compartment: 'Mitochondria · cytoplasm · ER',
    summary: 'Lactate, glycerol and amino-acid carbon are converted back to glucose through PEPCK and G6Pase control points.',
    metabolites: ['Lactate', 'Alanine', 'Glycerol', 'OAA', 'PEP', 'G6P', 'Glucose'],
    enzymes: ['PCK1', 'G6PC', 'PDK4'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 1, synthesisRate: 0.96, role: 'Dominant glucose production organ' },
      { ref: 'kidney', state: 'up', weight: 0.68, synthesisRate: 0.66, role: 'Renal gluconeogenesis during fasting/acidosis' },
      { ref: 'intestine', state: 'dysregulated', weight: 0.34, synthesisRate: 0.34, role: 'Enterocyte glucose production signal' },
    ],
  },
  {
    id: 'pentose_phosphate',
    name: 'Pentose Phosphate Pathway',
    category: 'Redox and ribose',
    compartment: 'Cytoplasm',
    summary: 'G6P is routed to NADPH and ribose-5-phosphate for antioxidant defense, lipid synthesis and nucleotide production.',
    metabolites: ['G6P', '6PG', 'Ribulose-5P', 'Ribose-5P', 'NADPH'],
    enzymes: ['G6PD', 'GCLC', 'SHMT2'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.86, synthesisRate: 0.84, role: 'NADPH for lipogenesis and detox' },
      { ref: 'adipose', state: 'up', weight: 0.74, synthesisRate: 0.72, role: 'NADPH for fatty-acid synthesis' },
      { ref: 'bone_marrow', state: 'up', weight: 0.72, synthesisRate: 0.72, role: 'Erythroid redox and nucleotide demand' },
      { ref: 'breast', state: 'up', weight: 0.62, synthesisRate: 0.68, role: 'Proliferative ribose and NADPH supply' },
    ],
  },
  {
    id: 'fatty_acid_oxidation',
    name: 'Fatty Acid β-Oxidation',
    category: 'Lipid degradation',
    compartment: 'Mitochondria · peroxisomes',
    summary: 'Acyl-carnitines enter mitochondria and are shortened into acetyl-CoA, NADH and FADH2 for ATP and ketone production.',
    metabolites: ['Fatty acid', 'Acyl-CoA', 'Acyl-carnitine', 'Acetyl-CoA', 'NADH'],
    enzymes: ['CPT1A', 'HADHA', 'BDH1'],
    tissueFlux: [
      { ref: 'heart', state: 'up', weight: 0.94, synthesisRate: 0.94, role: 'Preferred oxidative fuel in adult myocardium' },
      { ref: 'liver', state: 'dysregulated', weight: 0.86, synthesisRate: 0.84, role: 'FAO feeds ketogenesis and VLDL balance' },
      { ref: 'muscle', state: 'down', weight: 0.72, synthesisRate: 0.68, role: 'Reduced oxidation in insulin resistance' },
      { ref: 'kidney', state: 'up', weight: 0.62, synthesisRate: 0.62, role: 'Tubular fatty-acid energy supply' },
    ],
  },
  {
    id: 'lipogenesis',
    name: 'Fatty Acid Biosynthesis',
    category: 'Lipid biosynthesis',
    compartment: 'Cytoplasm',
    summary: 'Citrate-derived acetyl-CoA is converted to malonyl-CoA and elongated into palmitate and other fatty acids.',
    metabolites: ['Citrate', 'Acetyl-CoA', 'Malonyl-CoA', 'Palmitate', 'NADPH'],
    enzymes: ['ACACA', 'FASN', 'SCD'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.92, synthesisRate: 0.9, role: 'De novo lipogenesis and VLDL packaging' },
      { ref: 'adipose', state: 'up', weight: 0.82, synthesisRate: 0.82, role: 'Fat storage expansion' },
      { ref: 'breast', state: 'up', weight: 0.68, synthesisRate: 0.74, role: 'Membrane synthesis in proliferative context' },
    ],
  },
  {
    id: 'ketone_bodies',
    name: 'Ketone Body Metabolism',
    category: 'Fasting fuel',
    compartment: 'Liver mitochondria · peripheral mitochondria',
    summary: 'Acetyl-CoA is converted to acetoacetate and beta-hydroxybutyrate in liver, then consumed by brain, heart and muscle.',
    metabolites: ['Acetyl-CoA', 'HMG-CoA', 'Acetoacetate', 'beta-Hydroxybutyrate'],
    enzymes: ['BDH1', 'HMGCR', 'CPT1A'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.9, synthesisRate: 0.9, role: 'Primary ketone synthesis site' },
      { ref: 'heart', state: 'up', weight: 0.68, synthesisRate: 0.7, role: 'Efficient ketone oxidation' },
      { ref: 'brain', state: 'up', weight: 0.58, synthesisRate: 0.58, role: 'Fasting-adapted ketone utilization' },
      { ref: 'muscle', state: 'up', weight: 0.54, synthesisRate: 0.54, role: 'Peripheral ketone oxidation' },
    ],
  },
  {
    id: 'triglyceride_metabolism',
    name: 'Triacylglycerol Metabolism',
    category: 'Neutral lipid storage',
    compartment: 'Lipid droplets · ER',
    summary: 'Fatty acids and glycerol backbones cycle between storage, lipolysis and lipoprotein export.',
    metabolites: ['Glycerol-3P', 'DAG', 'TAG', 'Free fatty acid', 'Glycerol'],
    enzymes: ['DGAT2', 'LIPE', 'CPT1A'],
    tissueFlux: [
      { ref: 'adipose', state: 'up', weight: 1, synthesisRate: 0.96, role: 'Dominant lipid storage and release organ' },
      { ref: 'liver', state: 'dysregulated', weight: 0.86, synthesisRate: 0.82, role: 'Hepatic steatosis and VLDL output' },
      { ref: 'muscle', state: 'dysregulated', weight: 0.5, synthesisRate: 0.48, role: 'Intramyocellular lipid accumulation' },
    ],
  },
  {
    id: 'phospholipid_metabolism',
    name: 'Phospholipid / Sphingolipid Metabolism',
    category: 'Membrane lipids',
    compartment: 'ER · Golgi · membranes',
    summary: 'Phospholipid and sphingolipid remodeling tunes membrane composition, signaling lipids and stress responses.',
    metabolites: ['Phosphatidylcholine', 'DAG', 'Ceramide', 'Sphingosine-1P'],
    enzymes: ['SCD', 'DGAT2', 'GCLC'],
    tissueFlux: [
      { ref: 'brain', state: 'up', weight: 0.84, synthesisRate: 0.82, role: 'Myelin and synaptic membrane turnover' },
      { ref: 'liver', state: 'up', weight: 0.72, synthesisRate: 0.72, role: 'Lipoprotein and bile membrane lipid handling' },
      { ref: 'lungs', state: 'up', weight: 0.68, synthesisRate: 0.68, role: 'Surfactant phospholipid production' },
      { ref: 'breast', state: 'up', weight: 0.52, synthesisRate: 0.56, role: 'Proliferative membrane biomass' },
    ],
  },
  {
    id: 'cholesterol',
    name: 'Cholesterol / Mevalonate',
    category: 'Sterol metabolism',
    compartment: 'Cytoplasm · ER',
    summary: 'Acetyl-CoA enters mevalonate metabolism to produce sterols, isoprenoids and prenylation substrates.',
    metabolites: ['Acetyl-CoA', 'HMG-CoA', 'Mevalonate', 'Squalene', 'Cholesterol'],
    enzymes: ['HMGCR', 'CYP7A1', 'CYP11A1'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.9, synthesisRate: 0.88, role: 'Systemic cholesterol synthesis and export' },
      { ref: 'brain', state: 'up', weight: 0.64, synthesisRate: 0.62, role: 'Local CNS sterol turnover' },
      { ref: 'adipose', state: 'dysregulated', weight: 0.46, synthesisRate: 0.44, role: 'Sterol storage and endocrine adipocyte state' },
      { ref: 'breast', state: 'up', weight: 0.5, synthesisRate: 0.56, role: 'Mevalonate-linked proliferative signaling' },
    ],
  },
  {
    id: 'steroid_hormone',
    name: 'Steroid Hormone Biosynthesis',
    category: 'Hormones',
    compartment: 'Mitochondria · ER',
    summary: 'Cholesterol is converted into pregnenolone and downstream steroid hormones that shape endocrine programs.',
    metabolites: ['Cholesterol', 'Pregnenolone', 'Progesterone', 'Cortisol', 'Estrogens'],
    enzymes: ['CYP11A1', 'HMGCR', 'CYP3A4'],
    tissueFlux: [
      { ref: 'adipose', state: 'dysregulated', weight: 0.62, synthesisRate: 0.58, role: 'Peripheral steroid handling and aromatase context' },
      { ref: 'breast', state: 'dysregulated', weight: 0.58, synthesisRate: 0.58, role: 'Hormone-sensitive tissue response' },
      { ref: 'brain', state: 'neutral', weight: 0.34, synthesisRate: 0.32, role: 'Neurosteroid signaling context' },
    ],
  },
  {
    id: 'bile_acid',
    name: 'Bile Acid Synthesis',
    category: 'Liver lipid handling',
    compartment: 'Liver ER · mitochondria · intestine',
    summary: 'Cholesterol is hydroxylated, conjugated and cycled through the gut to support lipid absorption and metabolic signaling.',
    metabolites: ['Cholesterol', '7alpha-Hydroxycholesterol', 'Cholic acid', 'Bile salts'],
    enzymes: ['CYP7A1', 'UGT1A1', 'CYP3A4'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 1, synthesisRate: 0.96, role: 'Primary bile acid synthesis and conjugation' },
      { ref: 'intestine', state: 'dysregulated', weight: 0.76, synthesisRate: 0.72, role: 'Enterohepatic reabsorption and FXR/TGR5 signaling' },
    ],
  },
  {
    id: 'one_carbon',
    name: 'One-Carbon / Folate Cycle',
    category: 'Methyl and nucleotide supply',
    compartment: 'Cytoplasm · mitochondria',
    summary: 'Serine and folate metabolism provide one-carbon units for thymidylate, purines and methylation.',
    metabolites: ['Serine', 'Glycine', '5,10-methylene-THF', 'SAM', 'dTMP'],
    enzymes: ['SHMT2', 'TYMS', 'G6PD'],
    tissueFlux: [
      { ref: 'breast', state: 'up', weight: 0.76, synthesisRate: 0.82, role: 'Proliferative nucleotide demand' },
      { ref: 'bone_marrow', state: 'up', weight: 0.76, synthesisRate: 0.78, role: 'Hematopoietic DNA synthesis' },
      { ref: 'intestine', state: 'up', weight: 0.56, synthesisRate: 0.56, role: 'Rapid epithelial turnover' },
      { ref: 'liver', state: 'dysregulated', weight: 0.54, synthesisRate: 0.52, role: 'Methyl donor and folate processing' },
    ],
  },
  {
    id: 'purine',
    name: 'Purine Metabolism',
    category: 'Nucleotide metabolism',
    compartment: 'Cytoplasm',
    summary: 'Purines are synthesized, salvaged and degraded through ATP/GTP pools, uric acid and purinergic inflammatory cues.',
    metabolites: ['Ribose-5P', 'IMP', 'AMP', 'GMP', 'Hypoxanthine', 'Uric acid'],
    enzymes: ['XDH', 'G6PD', 'SHMT2'],
    tissueFlux: [
      { ref: 'bone_marrow', state: 'up', weight: 0.82, synthesisRate: 0.82, role: 'Immune and blood cell nucleotide demand' },
      { ref: 'spleen', state: 'up', weight: 0.76, synthesisRate: 0.76, role: 'Lymphocyte expansion and turnover' },
      { ref: 'liver', state: 'dysregulated', weight: 0.68, synthesisRate: 0.66, role: 'Purine catabolism and urate production' },
      { ref: 'kidney', state: 'dysregulated', weight: 0.56, synthesisRate: 0.52, role: 'Urate handling and excretion' },
    ],
  },
  {
    id: 'pyrimidine',
    name: 'Pyrimidine Metabolism',
    category: 'Nucleotide metabolism',
    compartment: 'Cytoplasm · mitochondria',
    summary: 'Pyrimidine synthesis couples mitochondrial DHODH activity to UMP, CTP and dTMP production.',
    metabolites: ['Carbamoyl phosphate', 'Orotate', 'UMP', 'CTP', 'dTMP'],
    enzymes: ['DHODH', 'TYMS', 'SHMT2'],
    tissueFlux: [
      { ref: 'bone_marrow', state: 'up', weight: 0.84, synthesisRate: 0.84, role: 'Hematopoietic DNA/RNA synthesis' },
      { ref: 'breast', state: 'up', weight: 0.72, synthesisRate: 0.78, role: 'Proliferation-linked nucleotide synthesis' },
      { ref: 'intestine', state: 'up', weight: 0.62, synthesisRate: 0.62, role: 'Epithelial renewal' },
      { ref: 'spleen', state: 'up', weight: 0.58, synthesisRate: 0.58, role: 'Activated immune cell expansion' },
    ],
  },
  {
    id: 'amino_acid_metabolism',
    name: 'Amino Acid Metabolism',
    category: 'Nitrogen and carbon',
    compartment: 'Cytoplasm · mitochondria',
    summary: 'Amino acids are transaminated, oxidized or redirected into neurotransmitters, one-carbon units and TCA intermediates.',
    metabolites: ['Glutamate', 'Alanine', 'Aspartate', 'Serine', 'alpha-KG', 'Glutamine'],
    enzymes: ['SHMT2', 'CPS1', 'ASS1'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.94, synthesisRate: 0.92, role: 'Central nitrogen and amino-acid carbon hub' },
      { ref: 'muscle', state: 'dysregulated', weight: 0.68, synthesisRate: 0.66, role: 'Alanine/glutamine export during stress' },
      { ref: 'brain', state: 'dysregulated', weight: 0.64, synthesisRate: 0.62, role: 'Glutamate/GABA and neurotransmitter balance' },
      { ref: 'intestine', state: 'up', weight: 0.54, synthesisRate: 0.54, role: 'Glutamine-fueled epithelial metabolism' },
    ],
  },
  {
    id: 'urea_cycle',
    name: 'Urea Cycle',
    category: 'Nitrogen disposal',
    compartment: 'Liver mitochondria · cytoplasm',
    summary: 'Ammonia and aspartate nitrogen enter the ornithine cycle to form urea and protect the brain from hyperammonemia.',
    metabolites: ['Ammonia', 'Carbamoyl phosphate', 'Citrulline', 'Argininosuccinate', 'Arginine', 'Urea'],
    enzymes: ['CPS1', 'ASS1', 'G6PC'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 1, synthesisRate: 1, role: 'Primary ureagenesis and ammonia detoxification' },
      { ref: 'kidney', state: 'dysregulated', weight: 0.34, synthesisRate: 0.32, role: 'Arginine and nitrogen handling support' },
      { ref: 'brain', state: 'down', weight: 0.28, synthesisRate: 0.24, role: 'Sensitive target when nitrogen disposal fails' },
    ],
  },
  {
    id: 'heme_porphyrin',
    name: 'Heme / Porphyrin Metabolism',
    category: 'Cofactor and oxygen',
    compartment: 'Mitochondria · cytoplasm',
    summary: 'Glycine and succinyl-CoA feed porphyrin synthesis; heme turnover links erythroid output, liver clearance and oxygen biology.',
    metabolites: ['Glycine', 'ALA', 'Porphobilinogen', 'Protoporphyrin IX', 'Heme', 'Bilirubin'],
    enzymes: ['ALAS2', 'UGT1A1', 'CPS1'],
    tissueFlux: [
      { ref: 'bone_marrow', state: 'up', weight: 1, synthesisRate: 0.96, role: 'Erythroid heme synthesis' },
      { ref: 'liver', state: 'up', weight: 0.76, synthesisRate: 0.74, role: 'Heme turnover and bilirubin conjugation' },
      { ref: 'spleen', state: 'up', weight: 0.62, synthesisRate: 0.58, role: 'RBC recycling and heme processing' },
    ],
  },
  {
    id: 'vitamin_coenzyme',
    name: 'Vitamins / Coenzymes',
    category: 'Cofactor metabolism',
    compartment: 'Systemic',
    summary: 'B vitamins and coenzymes support redox, one-carbon transfer, acyl transfer and mitochondrial enzyme activity.',
    metabolites: ['NAD+', 'FAD', 'CoA', 'THF', 'Biotin', 'PLP'],
    enzymes: ['PDHA1', 'SHMT2', 'CYP3A4'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.86, synthesisRate: 0.84, role: 'Cofactor storage and activation hub' },
      { ref: 'intestine', state: 'dysregulated', weight: 0.62, synthesisRate: 0.6, role: 'Absorption and microbiome-linked supply' },
      { ref: 'brain', state: 'up', weight: 0.52, synthesisRate: 0.5, role: 'Neurochemical cofactor dependence' },
      { ref: 'bone_marrow', state: 'up', weight: 0.5, synthesisRate: 0.5, role: 'Folate/B12-sensitive hematopoiesis' },
    ],
  },
  {
    id: 'catecholamine',
    name: 'Catecholamine Biosynthesis',
    category: 'Neurotransmitter metabolism',
    compartment: 'Cytoplasm · vesicles',
    summary: 'Tyrosine is hydroxylated and decarboxylated into dopamine, norepinephrine and epinephrine-like stress signals.',
    metabolites: ['Tyrosine', 'L-DOPA', 'Dopamine', 'Norepinephrine', 'Epinephrine'],
    enzymes: ['TH', 'COMT', 'CYP3A4'],
    tissueFlux: [
      { ref: 'brain', state: 'up', weight: 0.82, synthesisRate: 0.82, role: 'Dopaminergic and noradrenergic signaling' },
      { ref: 'heart', state: 'dysregulated', weight: 0.5, synthesisRate: 0.48, role: 'Adrenergic cardiac stress response' },
      { ref: 'liver', state: 'neutral', weight: 0.32, synthesisRate: 0.3, role: 'Catecholamine clearance support' },
    ],
  },
  {
    id: 'glutathione_redox',
    name: 'Glutathione / Redox Buffering',
    category: 'Redox defense',
    compartment: 'Cytoplasm · mitochondria',
    summary: 'NADPH and glutathione buffer reactive oxygen species, detox electrophiles and protect mitochondrial metabolism.',
    metabolites: ['Glutamate', 'Cysteine', 'GSH', 'GSSG', 'NADPH'],
    enzymes: ['GCLC', 'G6PD', 'UGT1A1'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 0.94, synthesisRate: 0.92, role: 'Detox and antioxidant reserve' },
      { ref: 'lungs', state: 'up', weight: 0.74, synthesisRate: 0.72, role: 'Oxidant barrier defense' },
      { ref: 'brain', state: 'dysregulated', weight: 0.62, synthesisRate: 0.58, role: 'Neuroinflammatory oxidative stress' },
      { ref: 'bone_marrow', state: 'up', weight: 0.56, synthesisRate: 0.56, role: 'Erythroid redox protection' },
    ],
  },
  {
    id: 'xenobiotic_detox',
    name: 'Xenobiotic / Drug Metabolism',
    category: 'Detoxification',
    compartment: 'ER · cytoplasm · canalicular membrane',
    summary: 'Phase I oxidation and Phase II conjugation transform compounds for biliary or renal clearance.',
    metabolites: ['Drug/compound', 'Hydroxylated intermediate', 'Glucuronide', 'Sulfate conjugate'],
    enzymes: ['CYP3A4', 'UGT1A1', 'GCLC'],
    tissueFlux: [
      { ref: 'liver', state: 'up', weight: 1, synthesisRate: 1, role: 'Primary CYP and conjugation clearance' },
      { ref: 'intestine', state: 'up', weight: 0.68, synthesisRate: 0.66, role: 'First-pass metabolism and transport' },
      { ref: 'kidney', state: 'up', weight: 0.56, synthesisRate: 0.54, role: 'Filtered metabolite excretion' },
      { ref: 'skin', state: 'neutral', weight: 0.28, synthesisRate: 0.24, role: 'Barrier exposure and minor metabolism' },
    ],
  },
];

export const METABOLIC_ROUTES: MetabolicRoute[] = [
  {
    id: 'glucose-carbon',
    name: 'Glucose carbon routing',
    tissue: 'Muscle · Liver · Tumor',
    steps: ['Glucose', 'G6P', 'Pyruvate', 'Acetyl-CoA', 'Citrate', 'ATP'],
    enzymes: ['HK2', 'PKM', 'LDHA', 'PDHA1'],
    pathways: ['glycolysis', 'pyruvate_metabolism', 'lactate_shuttle', 'tca_cycle', 'oxphos'],
  },
  {
    id: 'lipid-energy',
    name: 'Lipid energy axis',
    tissue: 'Adipose · Liver · Muscle',
    steps: ['Free fatty acid', 'Acyl-carnitine', 'Acetyl-CoA', 'Ketone bodies', 'Sterols'],
    enzymes: ['CPT1A', 'HADHA', 'ACACA', 'FASN', 'CYP7A1'],
    pathways: ['fatty_acid_oxidation', 'triglyceride_metabolism', 'lipogenesis', 'ketone_bodies', 'cholesterol', 'bile_acid'],
  },
  {
    id: 'growth-biomass',
    name: 'Growth and biomass supply',
    tissue: 'Breast · Immune · Marrow',
    steps: ['Serine', 'One-carbon pool', 'Purines', 'DNA repair', 'Membrane sterols'],
    enzymes: ['SHMT2', 'TYMS', 'DHODH', 'XDH', 'HMGCR'],
    pathways: ['one_carbon', 'purine', 'pyrimidine', 'phospholipid_metabolism', 'cholesterol', 'pi3k_her2'],
  },
  {
    id: 'nitrogen-redox-detox',
    name: 'Nitrogen, redox and clearance',
    tissue: 'Liver · Kidney · Marrow · Lung',
    steps: ['Amino acids', 'Ammonia', 'Urea', 'GSH', 'Conjugated metabolite'],
    enzymes: ['CPS1', 'ASS1', 'GCLC', 'G6PD', 'CYP3A4', 'UGT1A1'],
    pathways: ['amino_acid_metabolism', 'urea_cycle', 'heme_porphyrin', 'vitamin_coenzyme', 'glutathione_redox', 'xenobiotic_detox'],
  },
];

// ============================================================
// DISEASE PROGRAMS — built-in systems-biology stories
// ============================================================
export const PROGRAMS: DiseaseProgram[] = [
  {
    id: 'healthy_baseline',
    name: 'Healthy Metabolic Baseline',
    shortName: 'Healthy baseline',
    tagline: 'Reference homeostasis before disease or perturbation',
    narrative:
      'A normal starting state: tissues pulse at reference metabolic throughput, pathways sit near homeostatic set-points, and deviations are interpreted against this baseline.',
    systemFocus: 'Reference physiology',
    tissues: [
      { ref: 'brain', state: 'baseline', weight: 0.78, note: 'Stable glucose oxidation and neurotransmitter support' },
      { ref: 'heart', state: 'baseline', weight: 0.86, note: 'High steady mitochondrial ATP demand' },
      { ref: 'lungs', state: 'baseline', weight: 0.58, note: 'Surfactant lipid turnover and redox barrier defense' },
      { ref: 'liver', state: 'baseline', weight: 0.92, note: 'Balanced carbon, lipid, urea, bile acid and detox routing' },
      { ref: 'pancreas', state: 'baseline', weight: 0.58, note: 'Insulin/glucagon response within normal range' },
      { ref: 'intestine', state: 'baseline', weight: 0.62, note: 'Absorption, epithelial turnover and bile acid cycling' },
      { ref: 'kidney', state: 'baseline', weight: 0.66, note: 'Solute transport, excretion and renal gluconeogenesis reserve' },
      { ref: 'adipose', state: 'baseline', weight: 0.58, note: 'TAG storage/release in energy balance' },
      { ref: 'muscle', state: 'baseline', weight: 0.72, note: 'Insulin-sensitive glucose uptake and oxidative capacity' },
      { ref: 'bone_marrow', state: 'baseline', weight: 0.56, note: 'Hematopoietic nucleotide, heme and redox demand' },
    ],
    pathways: [
      { ref: 'glycolysis', state: 'baseline', weight: 0.66 },
      { ref: 'pyruvate_metabolism', state: 'baseline', weight: 0.62 },
      { ref: 'tca_cycle', state: 'baseline', weight: 0.78 },
      { ref: 'oxphos', state: 'baseline', weight: 0.82 },
      { ref: 'glycogen_metabolism', state: 'baseline', weight: 0.5 },
      { ref: 'gluconeogenesis', state: 'baseline', weight: 0.46 },
      { ref: 'pentose_phosphate', state: 'baseline', weight: 0.58 },
      { ref: 'fatty_acid_oxidation', state: 'baseline', weight: 0.64 },
      { ref: 'lipogenesis', state: 'baseline', weight: 0.48 },
      { ref: 'triglyceride_metabolism', state: 'baseline', weight: 0.52 },
      { ref: 'cholesterol', state: 'baseline', weight: 0.5 },
      { ref: 'bile_acid', state: 'baseline', weight: 0.44 },
      { ref: 'one_carbon', state: 'baseline', weight: 0.52 },
      { ref: 'purine', state: 'baseline', weight: 0.5 },
      { ref: 'pyrimidine', state: 'baseline', weight: 0.48 },
      { ref: 'amino_acid_metabolism', state: 'baseline', weight: 0.58 },
      { ref: 'urea_cycle', state: 'baseline', weight: 0.52 },
      { ref: 'heme_porphyrin', state: 'baseline', weight: 0.48 },
      { ref: 'vitamin_coenzyme', state: 'baseline', weight: 0.42 },
      { ref: 'glutathione_redox', state: 'baseline', weight: 0.5 },
      { ref: 'xenobiotic_detox', state: 'baseline', weight: 0.38 },
    ],
    genes: [
      { ref: 'HK2', state: 'baseline', weight: 0.52 },
      { ref: 'PDHA1', state: 'baseline', weight: 0.58 },
      { ref: 'G6PD', state: 'baseline', weight: 0.52 },
      { ref: 'CPT1A', state: 'baseline', weight: 0.56 },
      { ref: 'ACACA', state: 'baseline', weight: 0.42 },
      { ref: 'FASN', state: 'baseline', weight: 0.4 },
      { ref: 'HMGCR', state: 'baseline', weight: 0.44 },
      { ref: 'SHMT2', state: 'baseline', weight: 0.46 },
      { ref: 'CPS1', state: 'baseline', weight: 0.48 },
      { ref: 'ALAS2', state: 'baseline', weight: 0.42 },
      { ref: 'GCLC', state: 'baseline', weight: 0.44 },
      { ref: 'CYP3A4', state: 'baseline', weight: 0.36 },
    ],
  },
  {
    id: 'neuroinflammation',
    name: 'Neuroinflammation',
    shortName: 'Neuro-inflammation',
    tagline: 'Microglial priming and a leaky cytokine axis',
    narrative:
      'Chronic microglial activation drives IL-6 / TNF release in the CNS, recruits peripheral immune signaling, and amplifies hepatic acute-phase response.',
    systemFocus: 'Neuro-immune',
    tissues: [
      { ref: 'brain',       state: 'dysregulated', weight: 1.0,  note: 'Microglial activation, astrogliosis' },
      { ref: 'spleen',      state: 'up',           weight: 0.65, note: 'Peripheral immune mobilization' },
      { ref: 'liver',       state: 'up',           weight: 0.7,  note: 'IL-6 driven acute phase (CRP)' },
      { ref: 'bone_marrow', state: 'up',           weight: 0.55, note: 'Myeloid output increase' },
    ],
    pathways: [
      { ref: 'microglia',    state: 'up', weight: 1.0 },
      { ref: 'nfkb',         state: 'up', weight: 0.9 },
      { ref: 'jak_stat',     state: 'up', weight: 0.7 },
      { ref: 'tnf',          state: 'up', weight: 0.85 },
      { ref: 'complement',   state: 'up', weight: 0.6 },
    ],
    genes: [
      { ref: 'IL6',   state: 'up', weight: 0.95 },
      { ref: 'TNF',   state: 'up', weight: 0.85 },
      { ref: 'IL1B',  state: 'up', weight: 0.8 },
      { ref: 'TREM2', state: 'up', weight: 0.7 },
      { ref: 'GFAP',  state: 'up', weight: 0.75 },
      { ref: 'APOE',  state: 'dysregulated', weight: 0.6 },
      { ref: 'NFKB1', state: 'up', weight: 0.8 },
      { ref: 'CRP',   state: 'up', weight: 0.7 },
    ],
  },
  {
    id: 'insulin_resistance',
    name: 'Insulin Resistance',
    shortName: 'Metabolic dysfunction',
    tagline: 'Adipose-driven inflammation breaks the insulin axis',
    narrative:
      'Expanded adipose tissue secretes IL-6, TNF and altered adipokines; muscle and liver lose insulin sensitivity, β-cells compensate then fail.',
    systemFocus: 'Metabolic-immune',
    tissues: [
      { ref: 'adipose',  state: 'up',           weight: 1.0,  note: 'Adipocyte hypertrophy, macrophage infiltration' },
      { ref: 'liver',    state: 'dysregulated', weight: 0.85, note: 'Hepatic insulin resistance, gluconeogenesis ↑' },
      { ref: 'muscle',   state: 'down',         weight: 0.8,  note: 'GLUT4 translocation impaired' },
      { ref: 'pancreas', state: 'dysregulated', weight: 0.85, note: 'β-cell hypersecretion → exhaustion' },
      { ref: 'intestine',state: 'dysregulated', weight: 0.5,  note: 'Incretin axis altered' },
      { ref: 'brain',    state: 'down',         weight: 0.4,  note: 'Hypothalamic insulin/leptin resistance' },
    ],
    pathways: [
      { ref: 'insulin',   state: 'down', weight: 0.9 },
      { ref: 'ampk',      state: 'down', weight: 0.6 },
      { ref: 'mtor',      state: 'up',   weight: 0.7 },
      { ref: 'glycolysis',state: 'dysregulated', weight: 0.55 },
      { ref: 'pyruvate_metabolism', state: 'dysregulated', weight: 0.65 },
      { ref: 'glycogen_metabolism', state: 'down', weight: 0.66 },
      { ref: 'gluconeogenesis', state: 'up', weight: 0.78 },
      { ref: 'pentose_phosphate', state: 'up', weight: 0.54 },
      { ref: 'fatty_acid_oxidation', state: 'down', weight: 0.62 },
      { ref: 'lipogenesis', state: 'up', weight: 0.7 },
      { ref: 'triglyceride_metabolism', state: 'up', weight: 0.74 },
      { ref: 'tnf',       state: 'up',   weight: 0.65 },
      { ref: 'er_stress', state: 'up',   weight: 0.7 },
    ],
    genes: [
      { ref: 'INSR',  state: 'down', weight: 0.85 },
      { ref: 'IRS1',  state: 'down', weight: 0.9 },
      { ref: 'AKT1',  state: 'down', weight: 0.7 },
      { ref: 'GLUT4', state: 'down', weight: 0.85 },
      { ref: 'PPARG', state: 'dysregulated', weight: 0.7 },
      { ref: 'LEP',   state: 'up',   weight: 0.8 },
      { ref: 'TNF',   state: 'up',   weight: 0.7 },
      { ref: 'IL6',   state: 'up',   weight: 0.6 },
      { ref: 'CPT1A', state: 'down', weight: 0.55 },
      { ref: 'PDK4',  state: 'up', weight: 0.62 },
      { ref: 'PCK1',  state: 'up', weight: 0.7 },
      { ref: 'G6PC',  state: 'up', weight: 0.72 },
      { ref: 'ACACA', state: 'up', weight: 0.62 },
      { ref: 'FASN',  state: 'up', weight: 0.58 },
      { ref: 'G6PD',  state: 'up', weight: 0.5 },
      { ref: 'DGAT2', state: 'up', weight: 0.62 },
    ],
  },
  {
    id: 'her2_breast_cancer',
    name: 'HER2+ Breast Cancer',
    shortName: 'HER2+ breast',
    tagline: 'ERBB2 amplification drives PI3K-AKT-mTOR proliferation',
    narrative:
      'HER2 amplification in mammary epithelium drives constitutive PI3K-AKT-mTOR signaling, proliferative programs, and systemic dissemination risk to liver, bone and brain.',
    systemFocus: 'Oncogenic signaling',
    tissues: [
      { ref: 'breast',      state: 'dysregulated', weight: 1.0,  note: 'Primary tumor — ERBB2 amplified' },
      { ref: 'liver',       state: 'dysregulated', weight: 0.55, note: 'Common metastatic site' },
      { ref: 'bone_marrow', state: 'dysregulated', weight: 0.5,  note: 'Bone metastasis tropism' },
      { ref: 'brain',       state: 'dysregulated', weight: 0.45, note: 'CNS metastasis risk in HER2+' },
      { ref: 'lungs',       state: 'dysregulated', weight: 0.4,  note: 'Pulmonary metastasis risk' },
    ],
    pathways: [
      { ref: 'pi3k_her2', state: 'up', weight: 1.0 },
      { ref: 'mtor',      state: 'up', weight: 0.9 },
      { ref: 'estrogen',  state: 'dysregulated', weight: 0.55 },
      { ref: 'apoptosis', state: 'down', weight: 0.7 },
      { ref: 'glycolysis',state: 'up', weight: 0.6 },
      { ref: 'lactate_shuttle', state: 'up', weight: 0.66 },
      { ref: 'one_carbon', state: 'up', weight: 0.62 },
      { ref: 'pyrimidine', state: 'up', weight: 0.58 },
      { ref: 'pentose_phosphate', state: 'up', weight: 0.56 },
      { ref: 'phospholipid_metabolism', state: 'up', weight: 0.54 },
      { ref: 'cholesterol', state: 'up', weight: 0.5 },
    ],
    genes: [
      { ref: 'ERBB2', state: 'up', weight: 1.0 },
      { ref: 'AKT1',  state: 'up', weight: 0.85 },
      { ref: 'MKI67', state: 'up', weight: 0.9 },
      { ref: 'TP53',  state: 'dysregulated', weight: 0.7 },
      { ref: 'ESR1',  state: 'dysregulated', weight: 0.5 },
      { ref: 'BRCA1', state: 'dysregulated', weight: 0.4 },
      { ref: 'LDHA',  state: 'up', weight: 0.64 },
      { ref: 'SHMT2', state: 'up', weight: 0.58 },
      { ref: 'TYMS',  state: 'up', weight: 0.56 },
      { ref: 'DHODH', state: 'up', weight: 0.52 },
      { ref: 'G6PD',  state: 'up', weight: 0.5 },
      { ref: 'HMGCR', state: 'up', weight: 0.48 },
    ],
  },
  {
    id: 'metabolic_reprogramming',
    name: 'Whole-Body Metabolic Reprogramming',
    shortName: 'Metabolic flux atlas',
    tagline: 'Poster-scale carbon, lipid, nitrogen and redox routing across organs',
    narrative:
      'A whole-body metabolic pathway view projects glycolysis, TCA/ATP formation, lipid synthesis/degradation, nucleotides, amino-acid nitrogen, heme, cofactors and detox capacity onto the organs that actually carry the flux.',
    systemFocus: 'Integrated metabolism',
    tissues: [
      { ref: 'liver',       state: 'up',           weight: 1.0, note: 'Central carbon, lipid, urea, bile acid and xenobiotic hub' },
      { ref: 'muscle',      state: 'dysregulated', weight: 0.82, note: 'Glucose uptake, glycogen, lactate and fatty-acid oxidation demand' },
      { ref: 'adipose',     state: 'up',           weight: 0.78, note: 'TAG storage, lipolysis and lipogenesis pressure' },
      { ref: 'heart',       state: 'up',           weight: 0.76, note: 'FAO, TCA and oxidative phosphorylation intensity' },
      { ref: 'brain',       state: 'dysregulated', weight: 0.72, note: 'Glucose, ketone, neurotransmitter and redox sensitivity' },
      { ref: 'kidney',      state: 'up',           weight: 0.62, note: 'Gluconeogenesis, excretion and mitochondrial transport load' },
      { ref: 'bone_marrow', state: 'up',           weight: 0.6, note: 'Nucleotide, heme and redox synthesis for hematopoiesis' },
      { ref: 'intestine',   state: 'dysregulated', weight: 0.56, note: 'Bile acid cycling, absorption and first-pass metabolism' },
      { ref: 'lungs',       state: 'up',           weight: 0.42, note: 'Surfactant lipids and oxidative barrier defense' },
    ],
    pathways: [
      { ref: 'glycolysis', state: 'up', weight: 0.82 },
      { ref: 'pyruvate_metabolism', state: 'dysregulated', weight: 0.76 },
      { ref: 'tca_cycle', state: 'up', weight: 0.88 },
      { ref: 'oxphos', state: 'up', weight: 0.92 },
      { ref: 'glycogen_metabolism', state: 'dysregulated', weight: 0.58 },
      { ref: 'gluconeogenesis', state: 'up', weight: 0.64 },
      { ref: 'pentose_phosphate', state: 'up', weight: 0.72 },
      { ref: 'fatty_acid_oxidation', state: 'dysregulated', weight: 0.74 },
      { ref: 'lipogenesis', state: 'up', weight: 0.68 },
      { ref: 'triglyceride_metabolism', state: 'up', weight: 0.66 },
      { ref: 'ketone_bodies', state: 'up', weight: 0.58 },
      { ref: 'phospholipid_metabolism', state: 'up', weight: 0.58 },
      { ref: 'cholesterol', state: 'up', weight: 0.62 },
      { ref: 'steroid_hormone', state: 'dysregulated', weight: 0.44 },
      { ref: 'bile_acid', state: 'up', weight: 0.56 },
      { ref: 'one_carbon', state: 'up', weight: 0.62 },
      { ref: 'purine', state: 'up', weight: 0.62 },
      { ref: 'pyrimidine', state: 'up', weight: 0.6 },
      { ref: 'amino_acid_metabolism', state: 'up', weight: 0.74 },
      { ref: 'urea_cycle', state: 'up', weight: 0.66 },
      { ref: 'heme_porphyrin', state: 'up', weight: 0.56 },
      { ref: 'vitamin_coenzyme', state: 'up', weight: 0.52 },
      { ref: 'catecholamine', state: 'dysregulated', weight: 0.42 },
      { ref: 'glutathione_redox', state: 'up', weight: 0.64 },
      { ref: 'xenobiotic_detox', state: 'up', weight: 0.54 },
    ],
    genes: [
      { ref: 'HK2', state: 'up', weight: 0.7 },
      { ref: 'PKM', state: 'up', weight: 0.7 },
      { ref: 'LDHA', state: 'dysregulated', weight: 0.62 },
      { ref: 'PDHA1', state: 'up', weight: 0.74 },
      { ref: 'PDK4', state: 'dysregulated', weight: 0.58 },
      { ref: 'G6PD', state: 'up', weight: 0.78 },
      { ref: 'GYS1', state: 'dysregulated', weight: 0.5 },
      { ref: 'PYGL', state: 'up', weight: 0.5 },
      { ref: 'PCK1', state: 'up', weight: 0.58 },
      { ref: 'G6PC', state: 'up', weight: 0.58 },
      { ref: 'CPT1A', state: 'dysregulated', weight: 0.68 },
      { ref: 'HADHA', state: 'up', weight: 0.62 },
      { ref: 'ACACA', state: 'up', weight: 0.6 },
      { ref: 'FASN', state: 'up', weight: 0.6 },
      { ref: 'HMGCR', state: 'up', weight: 0.58 },
      { ref: 'CYP7A1', state: 'up', weight: 0.5 },
      { ref: 'SHMT2', state: 'up', weight: 0.62 },
      { ref: 'TYMS', state: 'up', weight: 0.56 },
      { ref: 'DHODH', state: 'up', weight: 0.54 },
      { ref: 'CPS1', state: 'up', weight: 0.62 },
      { ref: 'ASS1', state: 'up', weight: 0.54 },
      { ref: 'ALAS2', state: 'up', weight: 0.5 },
      { ref: 'GCLC', state: 'up', weight: 0.58 },
      { ref: 'CYP3A4', state: 'up', weight: 0.52 },
      { ref: 'UGT1A1', state: 'up', weight: 0.52 },
    ],
  },
  {
    id: 'viral_immune',
    name: 'Systemic Viral Response',
    shortName: 'Antiviral state',
    tagline: 'Type-I interferon cascade across barrier and lymphoid tissues',
    narrative:
      'Respiratory viral entry triggers a type-I IFN program in lung epithelium that propagates to spleen, marrow and liver — JAK-STAT-driven ISG expression and acute-phase response.',
    systemFocus: 'Antiviral immunity',
    tissues: [
      { ref: 'lungs',       state: 'dysregulated', weight: 1.0, note: 'Site of viral entry, ACE2+ epithelium' },
      { ref: 'spleen',      state: 'up', weight: 0.85, note: 'Lymphocyte activation' },
      { ref: 'bone_marrow', state: 'up', weight: 0.7,  note: 'Emergency myelopoiesis' },
      { ref: 'liver',       state: 'up', weight: 0.7,  note: 'Acute phase reactants ↑' },
      { ref: 'heart',       state: 'dysregulated', weight: 0.45, note: 'Cytokine-mediated myocardial stress' },
      { ref: 'brain',       state: 'dysregulated', weight: 0.4, note: 'Neuro-COVID style symptoms' },
    ],
    pathways: [
      { ref: 'ifn_response', state: 'up', weight: 1.0 },
      { ref: 'jak_stat',     state: 'up', weight: 0.95 },
      { ref: 'nfkb',         state: 'up', weight: 0.7 },
      { ref: 'complement',   state: 'up', weight: 0.65 },
      { ref: 'apoptosis',    state: 'up', weight: 0.5 },
      { ref: 'glycolysis',   state: 'up', weight: 0.62 },
      { ref: 'purine',       state: 'dysregulated', weight: 0.45 },
    ],
    genes: [
      { ref: 'ISG15', state: 'up', weight: 1.0 },
      { ref: 'MX1',   state: 'up', weight: 0.95 },
      { ref: 'OAS1',  state: 'up', weight: 0.9 },
      { ref: 'STAT1', state: 'up', weight: 0.9 },
      { ref: 'IFNG',  state: 'up', weight: 0.8 },
      { ref: 'IL6',   state: 'up', weight: 0.7 },
      { ref: 'ACE2',  state: 'dysregulated', weight: 0.6 },
      { ref: 'CRP',   state: 'up', weight: 0.7 },
      { ref: 'HK2',   state: 'up', weight: 0.55 },
      { ref: 'XDH',   state: 'up', weight: 0.45 },
    ],
  },
];

// Convenience lookup maps
export const TISSUE_BY_ID  = Object.fromEntries(TISSUES.map(t => [t.id, t])) as Record<string, Tissue>;
export const PATHWAY_BY_ID = Object.fromEntries(PATHWAYS.map(p => [p.id, p])) as Record<string, Pathway>;
export const GENE_BY_ID    = Object.fromEntries(GENES.map(g => [g.id, g])) as Record<string, Gene>;
export const PROGRAM_BY_ID = Object.fromEntries(PROGRAMS.map(p => [p.id, p])) as Record<string, DiseaseProgram>;
