import { Intervention, InterventionCategory } from './types';

export const INTERVENTION_CATEGORIES: InterventionCategory[] = [
  'Metabolic / MASLD',
  'Diabetes / insulin resistance',
  'Inflammatory / immune',
  'Oncology signaling',
  'Neuroinflammation',
  'Antiviral / host response',
  'Mitochondrial / redox',
];

export const INTERVENTIONS: Intervention[] = [
  {
    id: 'metformin',
    name: 'Metformin',
    subtitle: 'Biguanide · AMPK bias',
    category: 'Diabetes / insulin resistance',
    targets: [{ label: 'Liver', kind: 'tissue', ref: 'liver' }, { label: 'AMPK', kind: 'pathway', ref: 'ampk' }],
    mechanisms: ['AMPK activation', 'Hepatic glucose output down', 'Insulin signaling relief'],
    impact: ['Gluconeogenesis ↓', 'Insulin sensitivity ↑'],
    tissueEffects: [
      { ref: 'liver', direction: 'decrease', magnitude: 0.18, note: 'Suppresses modeled hepatic glucose production pressure.' },
      { ref: 'muscle', direction: 'stabilize', magnitude: 0.09, note: 'Improves peripheral insulin response in the demo model.' },
    ],
    pathwayEffects: [
      { ref: 'gluconeogenesis', direction: 'decrease', magnitude: 0.22, note: 'PEPCK/G6Pase axis pressure reduced.' },
      { ref: 'ampk', direction: 'increase', magnitude: 0.2, note: 'Energy-sensing tone increased.' },
    ],
    observableEffects: { glucose: -0.24, insulinSensitivity: 0.18, liverFat: -0.08, inflammation: -0.05 },
    score: 0.72,
    contraindicationNote: 'Demo placeholder: review renal function and lactic acidosis risk in real clinical contexts.',
  },
  {
    id: 'resmetirom',
    name: 'Resmetirom',
    subtitle: 'THR-β agonist · hepatic lipid',
    category: 'Metabolic / MASLD',
    targets: [{ label: 'Liver', kind: 'tissue', ref: 'liver' }, { label: 'THR-β', kind: 'receptor' }],
    mechanisms: ['Hepatic β-oxidation up', 'Liver fat burden down', 'Lipoprotein handling improved'],
    impact: ['Liver fat ↓', 'Mitochondrial lipid flux ↑'],
    tissueEffects: [{ ref: 'liver', direction: 'decrease', magnitude: 0.2, note: 'Reduces hepatic steatosis pressure.' }],
    pathwayEffects: [
      { ref: 'fatty_acid_oxidation', direction: 'increase', magnitude: 0.18, note: 'FAO throughput increased.' },
      { ref: 'triglyceride_metabolism', direction: 'decrease', magnitude: 0.16, note: 'Neutral lipid storage pressure reduced.' },
    ],
    observableEffects: { liverFat: -0.28, oxidativeStress: -0.06, insulinSensitivity: 0.05 },
    score: 0.68,
    contraindicationNote: 'Demo placeholder: thyroid axis and hepatic status need real-world review.',
  },
  {
    id: 'empagliflozin',
    name: 'Empagliflozin',
    subtitle: 'SGLT2 inhibitor · renal glucose',
    category: 'Diabetes / insulin resistance',
    targets: [{ label: 'Kidney', kind: 'tissue', ref: 'kidney' }, { label: 'SGLT2', kind: 'protein' }],
    mechanisms: ['Glucosuria up', 'Plasma glucose down', 'Cardiorenal stress relief'],
    impact: ['Glucose ↓', 'Cardiorenal pressure ↓'],
    tissueEffects: [
      { ref: 'kidney', direction: 'stabilize', magnitude: 0.12, note: 'Renal glucose handling shifted.' },
      { ref: 'heart', direction: 'decrease', magnitude: 0.08, note: 'Modeled hemodynamic/cardiometabolic relief.' },
    ],
    pathwayEffects: [{ ref: 'glycolysis', direction: 'decrease', magnitude: 0.08, note: 'Reduced circulating glucose load.' }],
    observableEffects: { glucose: -0.18, insulinSensitivity: 0.08, liverFat: -0.04, stability: 0.1 },
    score: 0.61,
    contraindicationNote: 'Demo placeholder: volume status, ketoacidosis risk, and renal indication require review.',
  },
  {
    id: 'semaglutide',
    name: 'Semaglutide',
    subtitle: 'GLP-1 receptor agonist',
    category: 'Diabetes / insulin resistance',
    targets: [{ label: 'Intestine', kind: 'tissue', ref: 'intestine' }, { label: 'Pancreas', kind: 'tissue', ref: 'pancreas' }],
    mechanisms: ['Glucose-dependent insulin up', 'Appetite/adiposity pressure down', 'Hepatic fat pressure down'],
    impact: ['Adiposity ↓', 'Insulin sensitivity ↑'],
    tissueEffects: [
      { ref: 'adipose', direction: 'decrease', magnitude: 0.22, note: 'Adiposity-linked inflammatory pressure reduced.' },
      { ref: 'pancreas', direction: 'stabilize', magnitude: 0.14, note: 'β-cell demand stabilized in the demo model.' },
      { ref: 'liver', direction: 'decrease', magnitude: 0.12, note: 'Hepatic lipid/glucose load reduced indirectly.' },
    ],
    pathwayEffects: [
      { ref: 'insulin', direction: 'increase', magnitude: 0.18, note: 'Insulin-axis response improved.' },
      { ref: 'triglyceride_metabolism', direction: 'decrease', magnitude: 0.12, note: 'Storage pressure reduced.' },
    ],
    observableEffects: { glucose: -0.2, insulinSensitivity: 0.22, liverFat: -0.16, inflammation: -0.08 },
    score: 0.76,
    contraindicationNote: 'Demo placeholder: GI tolerability and endocrine contraindications require review.',
  },
  {
    id: 'tirzepatide',
    name: 'Tirzepatide',
    subtitle: 'GIP / GLP-1 co-agonist',
    category: 'Diabetes / insulin resistance',
    targets: [{ label: 'Pancreas', kind: 'tissue', ref: 'pancreas' }, { label: 'Adipose', kind: 'tissue', ref: 'adipose' }],
    mechanisms: ['Incretin signaling up', 'Adiposity pressure down', 'Insulin sensitivity up'],
    impact: ['Glucose ↓', 'Liver fat ↓'],
    tissueEffects: [
      { ref: 'adipose', direction: 'decrease', magnitude: 0.26, note: 'Adipose inflammatory load reduced.' },
      { ref: 'liver', direction: 'decrease', magnitude: 0.15, note: 'Hepatic substrate overflow reduced.' },
    ],
    pathwayEffects: [{ ref: 'insulin', direction: 'increase', magnitude: 0.22, note: 'Modeled insulin response improved.' }],
    observableEffects: { glucose: -0.24, insulinSensitivity: 0.26, liverFat: -0.2, inflammation: -0.08 },
    score: 0.79,
    contraindicationNote: 'Demo placeholder: endocrine and GI precautions are not modeled.',
  },
  {
    id: 'pioglitazone',
    name: 'Pioglitazone',
    subtitle: 'PPARγ agonist',
    category: 'Metabolic / MASLD',
    targets: [{ label: 'Adipose', kind: 'tissue', ref: 'adipose' }, { label: 'PPARG', kind: 'gene', ref: 'PPARG' }],
    mechanisms: ['Adipose storage remodeling', 'Insulin sensitivity up', 'Ectopic lipid pressure down'],
    impact: ['Muscle glucose uptake ↑', 'Hepatic lipotoxicity ↓'],
    tissueEffects: [
      { ref: 'adipose', direction: 'stabilize', magnitude: 0.14, note: 'Adipose storage becomes less inflammatory.' },
      { ref: 'muscle', direction: 'stabilize', magnitude: 0.16, note: 'Peripheral insulin response improves.' },
    ],
    pathwayEffects: [{ ref: 'insulin', direction: 'increase', magnitude: 0.2, note: 'Insulin signaling pressure improves.' }],
    observableEffects: { insulinSensitivity: 0.24, liverFat: -0.1, inflammation: -0.04 },
    score: 0.58,
    contraindicationNote: 'Demo placeholder: edema, heart failure risk, and fracture risk are not modeled.',
  },
  {
    id: 'obeticholic_acid',
    name: 'Obeticholic Acid',
    subtitle: 'FXR agonist · bile acid axis',
    category: 'Metabolic / MASLD',
    targets: [{ label: 'Liver', kind: 'tissue', ref: 'liver' }, { label: 'Bile acids', kind: 'pathway', ref: 'bile_acid' }],
    mechanisms: ['FXR tone up', 'Bile-acid synthesis feedback', 'Fibro-inflammatory pressure down'],
    impact: ['Bile acid cycling ↔', 'Hepatic inflammation ↓'],
    tissueEffects: [{ ref: 'liver', direction: 'decrease', magnitude: 0.13, note: 'Hepatic inflammatory pressure lowered.' }],
    pathwayEffects: [
      { ref: 'bile_acid', direction: 'stabilize', magnitude: 0.2, note: 'Enterohepatic feedback stabilized.' },
      { ref: 'tnf', direction: 'decrease', magnitude: 0.08, note: 'Inflammatory tone reduced.' },
    ],
    observableEffects: { liverFat: -0.08, inflammation: -0.12, stability: 0.08 },
    score: 0.52,
    contraindicationNote: 'Demo placeholder: cholestatic risk and lipid changes need separate review.',
  },
  {
    id: 'tocilizumab',
    name: 'Tocilizumab',
    subtitle: 'IL-6R antibody',
    category: 'Inflammatory / immune',
    targets: [{ label: 'IL6', kind: 'gene', ref: 'IL6' }, { label: 'JAK-STAT', kind: 'pathway', ref: 'jak_stat' }],
    mechanisms: ['IL-6 receptor signaling down', 'Acute phase output down', 'Systemic inflammation down'],
    impact: ['CRP-like signal ↓', 'Immune tone ↓'],
    tissueEffects: [
      { ref: 'liver', direction: 'decrease', magnitude: 0.15, note: 'Acute phase hepatic output reduced.' },
      { ref: 'spleen', direction: 'decrease', magnitude: 0.12, note: 'Immune activation pressure reduced.' },
    ],
    pathwayEffects: [
      { ref: 'jak_stat', direction: 'decrease', magnitude: 0.22, note: 'Cytokine signaling suppressed.' },
      { ref: 'nfkb', direction: 'decrease', magnitude: 0.1, note: 'Secondary inflammatory tone reduced.' },
    ],
    observableEffects: { inflammation: -0.28, stability: 0.07 },
    score: 0.64,
    contraindicationNote: 'Demo placeholder: infection risk and lab monitoring are not represented.',
  },
  {
    id: 'adalimumab',
    name: 'Adalimumab',
    subtitle: 'TNF antibody',
    category: 'Inflammatory / immune',
    targets: [{ label: 'TNF', kind: 'gene', ref: 'TNF' }, { label: 'TNF signaling', kind: 'pathway', ref: 'tnf' }],
    mechanisms: ['TNF bioactivity down', 'NF-κB drive down', 'Peripheral inflammatory relay down'],
    impact: ['Inflammation ↓', 'Tissue immune pressure ↓'],
    tissueEffects: [
      { ref: 'spleen', direction: 'decrease', magnitude: 0.14, note: 'Immune relay reduced.' },
      { ref: 'skin', direction: 'decrease', magnitude: 0.1, note: 'Barrier inflammation signal reduced.' },
    ],
    pathwayEffects: [
      { ref: 'tnf', direction: 'decrease', magnitude: 0.24, note: 'TNF signaling directly inhibited.' },
      { ref: 'nfkb', direction: 'decrease', magnitude: 0.14, note: 'NF-kB downstream pressure reduced.' },
    ],
    observableEffects: { inflammation: -0.25, stability: 0.05 },
    score: 0.6,
    contraindicationNote: 'Demo placeholder: infection, TB, and malignancy precautions are not modeled.',
  },
  {
    id: 'baricitinib',
    name: 'Baricitinib',
    subtitle: 'JAK1/2 inhibitor',
    category: 'Inflammatory / immune',
    targets: [{ label: 'JAK-STAT', kind: 'pathway', ref: 'jak_stat' }, { label: 'Bone marrow', kind: 'tissue', ref: 'bone_marrow' }],
    mechanisms: ['Cytokine relay down', 'IFN/JAK signaling down', 'Myeloid activation pressure down'],
    impact: ['Immune activation ↓', 'Inflammatory tone ↓'],
    tissueEffects: [{ ref: 'bone_marrow', direction: 'decrease', magnitude: 0.12, note: 'Hematopoietic inflammatory signaling reduced.' }],
    pathwayEffects: [
      { ref: 'jak_stat', direction: 'decrease', magnitude: 0.26, note: 'JAK-STAT arm inhibited.' },
      { ref: 'ifn_response', direction: 'decrease', magnitude: 0.14, note: 'IFN-like signaling reduced.' },
    ],
    observableEffects: { inflammation: -0.22, stability: 0.04 },
    score: 0.57,
    contraindicationNote: 'Demo placeholder: thrombotic/infectious risk not represented.',
  },
  {
    id: 'trastuzumab',
    name: 'Trastuzumab',
    subtitle: 'HER2 antibody',
    category: 'Oncology signaling',
    targets: [{ label: 'Breast', kind: 'tissue', ref: 'breast' }, { label: 'ERBB2', kind: 'gene', ref: 'ERBB2' }],
    mechanisms: ['HER2 receptor signaling down', 'PI3K-AKT drive down', 'Tumor burden pressure down'],
    impact: ['HER2 signaling ↓', 'Proliferation ↓'],
    tissueEffects: [{ ref: 'breast', direction: 'decrease', magnitude: 0.25, note: 'HER2-linked tumor signal pressure reduced.' }],
    pathwayEffects: [{ ref: 'pi3k_her2', direction: 'decrease', magnitude: 0.3, note: 'HER2/PI3K module inhibited.' }],
    observableEffects: { tumorBurden: -0.26, stability: 0.06 },
    score: 0.7,
    contraindicationNote: 'Demo placeholder: cardiotoxicity monitoring is outside this model.',
  },
  {
    id: 'olaparib',
    name: 'Olaparib',
    subtitle: 'PARP inhibitor',
    category: 'Oncology signaling',
    targets: [{ label: 'BRCA1 context', kind: 'gene', ref: 'BRCA1' }, { label: 'Breast', kind: 'tissue', ref: 'breast' }],
    mechanisms: ['DNA repair stress up in tumor context', 'Synthetic lethality pressure', 'Proliferation pressure down'],
    impact: ['Tumor signal ↓', 'DNA repair dependency ↑'],
    tissueEffects: [{ ref: 'breast', direction: 'decrease', magnitude: 0.2, note: 'BRCA-like tumor program pressure reduced.' }],
    pathwayEffects: [{ ref: 'apoptosis', direction: 'increase', magnitude: 0.16, note: 'Tumor-cell death pressure increased in demo context.' }],
    observableEffects: { tumorBurden: -0.2, oxidativeStress: 0.04 },
    score: 0.62,
    contraindicationNote: 'Demo placeholder: hematologic toxicity and genotype selection not modeled.',
  },
  {
    id: 'everolimus',
    name: 'Everolimus',
    subtitle: 'mTOR inhibitor',
    category: 'Oncology signaling',
    targets: [{ label: 'mTOR', kind: 'pathway', ref: 'mtor' }, { label: 'Breast', kind: 'tissue', ref: 'breast' }],
    mechanisms: ['mTORC1 output down', 'Protein synthesis drive down', 'Growth signaling pressure down'],
    impact: ['Proliferation ↓', 'Metabolic growth ↓'],
    tissueEffects: [{ ref: 'breast', direction: 'decrease', magnitude: 0.15, note: 'Growth-linked oncogenic pressure reduced.' }],
    pathwayEffects: [{ ref: 'mtor', direction: 'decrease', magnitude: 0.26, note: 'mTOR activity suppressed.' }],
    observableEffects: { tumorBurden: -0.16, glucose: 0.04 },
    score: 0.55,
    contraindicationNote: 'Demo placeholder: metabolic and immune adverse effects are simplified.',
  },
  {
    id: 'tamoxifen',
    name: 'Tamoxifen',
    subtitle: 'Selective estrogen receptor modulator',
    category: 'Oncology signaling',
    targets: [{ label: 'ESR1', kind: 'gene', ref: 'ESR1' }, { label: 'Breast', kind: 'tissue', ref: 'breast' }],
    mechanisms: ['Estrogen receptor transcription down', 'Hormone-sensitive growth pressure down'],
    impact: ['ER signaling ↓', 'Breast proliferation ↓'],
    tissueEffects: [{ ref: 'breast', direction: 'decrease', magnitude: 0.18, note: 'ER-linked growth signal reduced.' }],
    pathwayEffects: [{ ref: 'estrogen', direction: 'decrease', magnitude: 0.28, note: 'ER transcriptional program inhibited.' }],
    observableEffects: { tumorBurden: -0.18, stability: 0.04 },
    score: 0.58,
    contraindicationNote: 'Demo placeholder: thrombotic/endometrial risk not modeled.',
  },
  {
    id: 'fingolimod',
    name: 'Fingolimod',
    subtitle: 'S1P receptor modulator',
    category: 'Neuroinflammation',
    targets: [{ label: 'Brain', kind: 'tissue', ref: 'brain' }, { label: 'Spleen', kind: 'tissue', ref: 'spleen' }],
    mechanisms: ['Lymphocyte egress down', 'CNS inflammatory trafficking down'],
    impact: ['Neuroimmune pressure ↓', 'Peripheral immune relay ↓'],
    tissueEffects: [
      { ref: 'brain', direction: 'decrease', magnitude: 0.16, note: 'CNS inflammatory pressure reduced.' },
      { ref: 'spleen', direction: 'decrease', magnitude: 0.1, note: 'Lymphocyte trafficking relay reduced.' },
    ],
    pathwayEffects: [{ ref: 'microglia', direction: 'decrease', magnitude: 0.16, note: 'Neuroimmune activation reduced.' }],
    observableEffects: { inflammation: -0.13, neuroinflammation: -0.22, stability: 0.05 },
    score: 0.56,
    contraindicationNote: 'Demo placeholder: cardiac and infectious precautions are not modeled.',
  },
  {
    id: 'minocycline',
    name: 'Minocycline',
    subtitle: 'Microglial modulation prototype',
    category: 'Neuroinflammation',
    targets: [{ label: 'Brain', kind: 'tissue', ref: 'brain' }, { label: 'Microglia', kind: 'pathway', ref: 'microglia' }],
    mechanisms: ['Microglial activation down', 'Cytokine tone down', 'Redox stress down'],
    impact: ['Neuroinflammation ↓', 'Oxidative stress ↓'],
    tissueEffects: [{ ref: 'brain', direction: 'decrease', magnitude: 0.12, note: 'Microglial inflammatory pressure reduced.' }],
    pathwayEffects: [
      { ref: 'microglia', direction: 'decrease', magnitude: 0.2, note: 'Microglial activation dampened.' },
      { ref: 'glutathione_redox', direction: 'stabilize', magnitude: 0.08, note: 'Redox buffering stabilized.' },
    ],
    observableEffects: { neuroinflammation: -0.2, oxidativeStress: -0.08, inflammation: -0.07 },
    score: 0.45,
    contraindicationNote: 'Demo placeholder: translational evidence varies by indication.',
  },
  {
    id: 'remdesivir',
    name: 'Remdesivir',
    subtitle: 'Viral polymerase inhibitor',
    category: 'Antiviral / host response',
    targets: [{ label: 'Lungs', kind: 'tissue', ref: 'lungs' }, { label: 'IFN response', kind: 'pathway', ref: 'ifn_response' }],
    mechanisms: ['Viral replication pressure down', 'Secondary interferon load down'],
    impact: ['Viral burden ↓', 'Lung immune activation ↓'],
    tissueEffects: [{ ref: 'lungs', direction: 'decrease', magnitude: 0.15, note: 'Respiratory viral pressure reduced.' }],
    pathwayEffects: [{ ref: 'ifn_response', direction: 'decrease', magnitude: 0.14, note: 'Antiviral stress signal normalizes as burden falls.' }],
    observableEffects: { viralLoad: -0.28, inflammation: -0.08, stability: 0.06 },
    score: 0.5,
    contraindicationNote: 'Demo placeholder: timing, renal/hepatic status, and indication are not modeled.',
  },
  {
    id: 'nirmatrelvir',
    name: 'Nirmatrelvir / Ritonavir',
    subtitle: 'Viral protease inhibition',
    category: 'Antiviral / host response',
    targets: [{ label: 'Lungs', kind: 'tissue', ref: 'lungs' }, { label: 'CYP3A4', kind: 'enzyme', ref: 'CYP3A4' }],
    mechanisms: ['Viral maturation down', 'Host antiviral load down', 'CYP interaction flag'],
    impact: ['Viral burden ↓', 'Interferon stress ↓'],
    tissueEffects: [{ ref: 'lungs', direction: 'decrease', magnitude: 0.18, note: 'Respiratory viral burden pressure reduced.' }],
    pathwayEffects: [
      { ref: 'ifn_response', direction: 'decrease', magnitude: 0.16, note: 'Interferon-like burden reduced downstream.' },
      { ref: 'xenobiotic_detox', direction: 'increase', magnitude: 0.16, note: 'Drug-interaction metabolism flag increased.' },
    ],
    observableEffects: { viralLoad: -0.32, inflammation: -0.08, stability: 0.05 },
    score: 0.54,
    contraindicationNote: 'Demo placeholder: major CYP3A interaction review required in real use.',
  },
  {
    id: 'nac',
    name: 'N-acetylcysteine',
    subtitle: 'Glutathione precursor',
    category: 'Mitochondrial / redox',
    targets: [{ label: 'Glutathione', kind: 'pathway', ref: 'glutathione_redox' }, { label: 'Liver', kind: 'tissue', ref: 'liver' }],
    mechanisms: ['Cysteine supply up', 'GSH buffering up', 'Oxidative stress down'],
    impact: ['Redox reserve ↑', 'Oxidative pressure ↓'],
    tissueEffects: [
      { ref: 'liver', direction: 'stabilize', magnitude: 0.1, note: 'Hepatic redox pressure stabilized.' },
      { ref: 'lungs', direction: 'stabilize', magnitude: 0.07, note: 'Respiratory redox burden reduced.' },
    ],
    pathwayEffects: [{ ref: 'glutathione_redox', direction: 'increase', magnitude: 0.24, note: 'Glutathione buffering increased.' }],
    observableEffects: { oxidativeStress: -0.24, inflammation: -0.05, stability: 0.08 },
    score: 0.48,
    contraindicationNote: 'Demo placeholder: route/indication-specific precautions not modeled.',
  },
  {
    id: 'coq10',
    name: 'Coenzyme Q10',
    subtitle: 'Electron transport cofactor',
    category: 'Mitochondrial / redox',
    targets: [{ label: 'OxPhos', kind: 'pathway', ref: 'oxphos' }, { label: 'Heart', kind: 'tissue', ref: 'heart' }],
    mechanisms: ['Electron transport support', 'Mitochondrial stress down'],
    impact: ['Mitochondrial function ↑', 'Oxidative stress ↓'],
    tissueEffects: [
      { ref: 'heart', direction: 'stabilize', magnitude: 0.1, note: 'Cardiac mitochondrial stress stabilized.' },
      { ref: 'muscle', direction: 'stabilize', magnitude: 0.08, note: 'Skeletal muscle oxidative capacity supported.' },
    ],
    pathwayEffects: [{ ref: 'oxphos', direction: 'increase', magnitude: 0.16, note: 'Electron transport capacity supported.' }],
    observableEffects: { oxidativeStress: -0.12, mitochondrialFunction: 0.18, stability: 0.08 },
    score: 0.42,
    contraindicationNote: 'Demo placeholder: supplement quality and indication are outside the model.',
  },
  {
    id: 'bezafibrate',
    name: 'Bezafibrate',
    subtitle: 'Pan-PPAR mitochondrial bias',
    category: 'Mitochondrial / redox',
    targets: [{ label: 'FAO', kind: 'pathway', ref: 'fatty_acid_oxidation' }, { label: 'Liver', kind: 'tissue', ref: 'liver' }],
    mechanisms: ['PPAR-driven FAO up', 'Lipid oxidation up', 'Mitochondrial capacity up'],
    impact: ['Fatty-acid oxidation ↑', 'Triglyceride pressure ↓'],
    tissueEffects: [
      { ref: 'liver', direction: 'decrease', magnitude: 0.12, note: 'Lipid stress pressure reduced.' },
      { ref: 'muscle', direction: 'stabilize', magnitude: 0.08, note: 'Oxidative lipid handling supported.' },
    ],
    pathwayEffects: [
      { ref: 'fatty_acid_oxidation', direction: 'increase', magnitude: 0.22, note: 'FAO throughput increased.' },
      { ref: 'triglyceride_metabolism', direction: 'decrease', magnitude: 0.12, note: 'TAG storage pressure reduced.' },
    ],
    observableEffects: { liverFat: -0.16, mitochondrialFunction: 0.14, oxidativeStress: -0.06 },
    score: 0.5,
    contraindicationNote: 'Demo placeholder: renal, hepatic, and lipid-panel context not modeled.',
  },
];

export const INTERVENTION_BY_ID = Object.fromEntries(INTERVENTIONS.map((intervention) => [intervention.id, intervention]));
